### ISSUE TITLE
http URIs

### ISSUE THREAD

**Issue by artebin** [smoneck/m3u2volumio#1]
Hi,
Thank you for your work :-)
One thing still needs to be improved, although it is maybe a limitation of volumio (I searched quite a while and I haven't found a solution):

The m3u playlist can contain a http URI and it is not a webradio but a regular file to be played in streaming (e.g. mp3 of a podcast for instance). In this special case, the user want to be able to pause the playback but it is not possible to pause the playback of a webradio in volumio...

And the "mpd" service expects everything to be accessed locally if I understood well.
So it seems there is no alternative to the "webradio" service when the URI is http.
Do you know about that?

**Comment by suuuehgi** [comment]
Hey!

You're welcome! :-) Yes, that would be nice. This is an implementation issue on Volumios side since Volumio distinguishes (mainly) between `webradio` and `mpd` as `service`. In the end both are being played using mpd and by looking at `var/log/volumio.log` I assume that this happens in a very similar manner but I didn't fully get how Volumio handles these cases ... Nevertheless is mpd capable of streaming (and pausing?) web content.

Cheers

**Comment by artebin** [comment]
As far as I understood the concept of "service" is internal to volumio. Indeed at the end it is played by mpd, but considering the (volumio) service "webradio" or "mpd", then volumio is not acting the same at HMI level (i.e. can I pause or not the playback?). Furthermore in its current implementation volumio expects all "mpd" service-based items of a playlist to be locally accessed, the URI is changed in consequence.

**Comment by suuuehgi** [comment]
Yes, that is what I was trying to express. :-) You can see that (no pause for webradio) e.g. in `Volumio2/app/index.js`:

```
1272     if (state.status != undefined) {
1273         if(state.status==='stop' || state.status==='pause')
1274         {
1275             return this.stateMachine.play();
1276         } else {
1277             if(state.trackType == 'webradio') {                                                                                               
1278                 return this.stateMachine.stop();
1279             } else {
1280                 return this.stateMachine.pause();
1281             }
1282         }
1283     }
```

Afaik Volumio even expects the files to be somewhere in `/mnt`.

Hence and in summary: I don't know any workaround.
